### ISSUE TITLE
trezorctl does not work on MacOS 12.3.1

### ISSUE THREAD

**Issue by sintezcs** [trezor/trezor-firmware#2275]
**Describe the bug**
trezorctl CLI does not work

**Info:**

-   OS: MacOS Monterey 12.3.1, Macbook Pro 14" M1
-   Python 3.9.10, virtualenv
-   trezor 0.13.0 python package

**How to reproduce**

1. Create and activate python virtualenv
2. `pip install trezor`
3. `trezorctl`
4. See error:
```
Traceback (most recent call last):
  File "/Users/xxx/.pyenv/versions/3.9.10/bin/trezorctl", line 5, in <module>
    from trezorlib.cli.trezorctl import cli
  File "/Users/xxx/.pyenv/versions/3.9.10/lib/python3.9/site-packages/trezorlib/cli/trezorctl.py", line 191, in <module>
    @cli.resultcallback()
AttributeError: 'TrezorctlGroup' object has no attribute 'resultcallback'
```

**Expected behavior**
trezorctl CLI starts up and displays help message

**Comment by prusnak** [comment]
Duplicate of https://github.com/trezor/trezor-firmware/issues/2199
