### ISSUE TITLE
U2F broken after UI refactor

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-firmware#448]
U2F is broken, probably due to bb2556a22cd3ffdc612a06da7d40eeb36a38de10:

```
Traceback (most recent call last):
  File "/home/andrew/firmware/core/src/apps/webauthn/__init__.py", line 329, in handle_reports
  File "/home/andrew/firmware/core/src/apps/webauthn/__init__.py", line 468, in dispatch_cmd
  File "/home/andrew/firmware/core/src/apps/webauthn/__init__.py", line 541, in msg_register
  File "/home/andrew/firmware/core/src/apps/webauthn/__init__.py", line 363, in setup
AttributeError: 'module' object has no attribute 'workflows'
```
