### PR TITLE
ci: fix core_unit_rust_test w/ ASAN

### PR DESCRIPTION
**Pull request by mmilata**
Fixes nightly pipeline failures caused (probably) by #4650.

```
error[E0463]: can't find crate for `ufmt_macros`
   --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ufmt-0.2.0/src/lib.rs:234:9
    |
234 | pub use ufmt_macros::uwrite;
    |         ^^^^^^^^^^^ can't find crate
```

https://github.com/trezor/trezor-firmware/actions/runs/13687506189/job/38274414168

### CODE REVIEW

**Comment by romanz** [comment]
Seems like an issue in `ufmt`:
```
~/src/ufmt $ git lg -1
* d95831b Jorge Aparicio:  (HEAD -> main, tag: ufmt-utils-v0.2.0, origin/main, origin/HEAD) ufmt-utils v0.2.0 (2 years, 7 months ago)

~/src/ufmt $ RUSTFLAGS='-Z sanitizer=address' cargo build
   Compiling proc-macro2 v1.0.94
   Compiling unicode-ident v1.0.18
   Compiling syn v1.0.109
   Compiling ufmt-write v0.1.0 (/home/rzeyde/src/ufmt/write)
   Compiling quote v1.0.39
   Compiling ufmt-macros v0.3.0 (/home/rzeyde/src/ufmt/macros)
   Compiling ufmt v0.2.0 (/home/rzeyde/src/ufmt)
error[E0463]: can't find crate for `ufmt_macros`
   --> src/lib.rs:234:9
    |
234 | pub use ufmt_macros::uwrite;
    |         ^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `ufmt_macros`
   --> src/lib.rs:239:9
    |
239 | pub use ufmt_macros::uwriteln;
    |         ^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `ufmt_macros`
   --> src/lib.rs:247:13
    |
247 |     pub use ufmt_macros::uDebug;
    |             ^^^^^^^^^^^ can't find crate

For more information about this error, try `rustc --explain E0463`.
error: could not compile `ufmt` (lib) due to 3 previous errors
```

**Review by romanz — APPROVED** [review]

**Comment by mmilata** [comment]
Apparently you need to specify an explicit `--target`: https://github.com/rust-lang/rust/issues/132109

Explains why building through Makefile works. Since we're not running what `cargo build` produces, let's just skip it in the ASAN CI job.
