### ISSUE TITLE
Crypto - make `tc_fault_handler` mandatory, document functions that need to be implemented

### ISSUE THREAD

**Issue by M1nd3r** [trezor/trezor-firmware#7223]
Make implementation of `consteq_fault_handler` (introduced in https://github.com/trezor/trezor-firmware/pull/7196) mandatory by the trezor-crypto users. 

### Details
- Change
```
__attribute__((weak)) void consteq_fault_handler(void) {
  // no-op by default; override in platform code
 }
```
to
```
void consteq_fault_handler(void);
```
so that it must be provided (if the implementation is not provided, the build will fail on `undefined reference to consteq_fault_handler`).

- Possibly move the definition to a separate header file instead of `consteq.c`.
- Add .md documentation for the trezor-crypto users - which functions have to be implemented. Might be a part of readme, or could be a separate doc referenced from readme.
- Take inspiration in libtropic (`include/libtropic_port.h`, `adding_host_platform.md`).
